
'use server';

import { supabase, supabaseError } from '@/lib/supabaseClient';
import type { UserProfileSupabase } from './auth'; // Use the Supabase profile type

// Ensure your 'events' table in Supabase matches this structure.
// Timestamps (start_date, end_date, registration_deadline, created_at) should be 'timestamptz'.
// fee is in Paisa.
export interface EventData {
    id?: string; // UUID, auto-generated by Supabase
    name: string;
    description: string;
    venue: string;
    rules?: string | null;
    start_date: string; // ISO string
    end_date: string;   // ISO string
    registration_deadline?: string | null; // ISO string
    event_type: 'individual' | 'group'; // Consider using an enum type in PostgreSQL
    min_team_size?: number | null;
    max_team_size?: number | null;
    fee: number; // Fee in Paisa
<<<<<<< HEAD
    created_at?: string; // ISO string, auto-generated by Supabase
    image_url?: string | null;
    image_storage_path?: string | null; // Path in Supabase Storage
    rules_pdf_url?: string | null; // For PDF rules
    rules_pdf_storage_path?: string | null; // Path in Supabase Storage for PDF rules
=======
    imageUrl?: string | null; // Modified to allow null
    createdAt?: Timestamp | string;
>>>>>>> f5b34cc (I see this error with the app, reported by NextJS, please fix it. The error is reported as HTML but presented visually to the user).)
}

// Structure for your 'participations' table.
// It should link to 'users' (user_id) and 'events' (event_id).
// payment_details could be a JSONB column.
export interface ParticipationData {
    id?: string; // Primary key for participation, will be auto-generated by Supabase
    user_id: string;
    event_id: string;
    event_name: string; // Denormalized for convenience
    user_name: string; // Denormalized
    user_email: string; // Denormalized
    user_phone: string; // Denormalized
    user_branch: string; // Denormalized
    user_semester: number; // Denormalized
    user_registration_number: string; // Denormalized
    payment_details?: { // Store as JSONB in Supabase
        order_id: string; // This would be the appOrderId for free events, or Cashfree's order_id for paid
        payment_id?: string | null; // Cashfree's payment_id, null for free events
        method: string; // 'Cashfree' or 'Free Registration'
    } | null;
    qr_code_data_uri?: string | null;
    participated_at?: string; // ISO string, timestamp of registration
    attended_at?: string | null; // ISO string, timestamp of actual attendance
}


/**
 * Records event participation in the 'participations' table.
 */
export async function participateInEvent(participationData: Omit<ParticipationData, 'id' | 'participated_at' | 'attended_at'>): Promise<{ success: boolean; participationId?: string; message?: string }> {
  console.log('[Supabase Service] participateInEvent invoked for event:', participationData.event_id, 'by user:', participationData.user_id);

  if (supabaseError || !supabase) {
    const errorMessage = `Participation service unavailable: Supabase client error - ${supabaseError?.message || 'Client not initialized'}.`;
    return { success: false, message: errorMessage };
  }

  try {
    // Check if user is already registered for the event
    const { data: existingParticipation, error: checkError } = await supabase
      .from('participations')
      .select('id')
      .eq('user_id', participationData.user_id)
      .eq('event_id', participationData.event_id)
      .limit(1)
      .single();

    if (checkError && checkError.code !== 'PGRST116') { // PGRST116: "Searched item was not found"
      throw checkError;
    }
    if (existingParticipation) {
      return { success: false, message: 'You are already registered for this event.' };
    }

    const docDataToInsert = {
      ...participationData,
      id: participationData.payment_details?.order_id, // Use the app-generated order ID as primary key
      participated_at: new Date().toISOString(),
      // qr_code_data_uri is already in participationData
    };
    
    const { data: newParticipation, error: insertError } = await supabase
      .from('participations')
      .insert(docDataToInsert)
      .select('id') 
      .single();

    if (insertError) throw insertError;

    if (!newParticipation || !newParticipation.id) {
        return { success: false, message: 'Participation recorded but failed to retrieve ID.' };
    }

    console.log('[Supabase Service] Participation recorded with ID:', newParticipation.id);
    return { success: true, participationId: newParticipation.id };

  } catch (error: any) {
    console.error('[Supabase Service Error] Error recording participation:', error.message, error.stack);
    let detailedMessage = `Could not record participation: ${error.message || 'Unknown database error'}`;
    if (error.code === '23505') { // Unique constraint violation
        detailedMessage = 'You are already registered for this event or there was a conflict with the order ID.';
    }
    return { success: false, message: detailedMessage };
  }
}

/**
 * Fetches user profile data from the 'users' table.
 */
 export async function getUserProfile(userId: string): Promise<{ success: boolean; data?: UserProfileSupabase; message?: string }> {
     console.log('[Supabase Service] getUserProfile invoked for user:', userId);

     if (supabaseError || !supabase) {
         return { success: false, message: `Supabase client error: ${supabaseError?.message || 'Client not initialized'}.` };
     }
     if (!userId) return { success: false, message: 'User ID is required.' };

     try {
         const { data, error } = await supabase
            .from('users') // Your public profiles table
            .select('*')
            .eq('id', userId)
            .single();

        if (error) {
            if (error.code === 'PGRST116') return { success: false, message: `User profile not found for user: ${userId}`};
            throw error;
        }
        return { success: true, data: data as UserProfileSupabase };

     } catch (error: any) {
         console.error('[Supabase Service Error] Error fetching user profile:', error.message, error.stack);
         return { success: false, message: `Failed to fetch user profile: ${error.message || 'Unknown database error'}` };
     }
 }


/**
 * Fetches all events/programs from the 'events' table, ordered by creation date.
 */
export async function getEvents(): Promise<{ success: boolean; events?: EventData[]; message?: string }> {
    console.log('[Supabase Service] getEvents invoked.');

    if (supabaseError || !supabase) {
      return { success: false, message: `Supabase client error: ${supabaseError?.message || 'Client not initialized'}.` };
    }

    try {
        const { data, error } = await supabase
            .from('events')
            .select('*')
            .order('created_at', { ascending: false });

<<<<<<< HEAD
        if (error) throw error;

        const events: EventData[] = data || [];
        console.log(`[Supabase Service] getEvents: Fetched ${events.length} items.`);
=======
        const events: EventData[] = [];
        querySnapshot.forEach((docSnap) => { // Renamed doc to docSnap
            const data = docSnap.data();

            const convertTimestamp = (timestamp: Timestamp | string | null | undefined): string | null => {
                 if (timestamp instanceof Timestamp) {
                    return timestamp.toDate().toISOString();
                 }
                 return typeof timestamp === 'string' ? timestamp : null;
            }

            events.push({
                id: docSnap.id,
                name: data.name,
                description: data.description,
                venue: data.venue,
                rules: data.rules,
                startDate: convertTimestamp(data.startDate)!, 
                endDate: convertTimestamp(data.endDate)!,     
                registrationDeadline: convertTimestamp(data.registrationDeadline),
                eventType: data.eventType,
                minTeamSize: data.minTeamSize,
                maxTeamSize: data.maxTeamSize,
                fee: data.fee,
                imageUrl: data.imageUrl === undefined ? null : data.imageUrl, // Handle undefined imageUrl
                createdAt: convertTimestamp(data.createdAt),
            } as EventData); // Added type assertion
        });

        console.log(`[Server Action] getEvents: Fetched ${events.length} items.`);
>>>>>>> f5b34cc (I see this error with the app, reported by NextJS, please fix it. The error is reported as HTML but presented visually to the user).)
        return { success: true, events };

    } catch (error: any) {
        console.error('[Supabase Service Error] Error fetching events:', error.message, error.stack);
        return { success: false, message: `Could not fetch items: ${error.message || 'Unknown database error'}` };
    }
}

/**
 * Fetches participation data for a specific user from the 'participations' table.
 */
export async function getParticipationData(userId: string): Promise<{ success: boolean; participations?: ParticipationData[]; message?: string }> {
  console.log('[Supabase Service] getParticipationData invoked for user:', userId);

  if (supabaseError || !supabase) {
    return { success: false, message: `Supabase client error: ${supabaseError?.message || 'Client not initialized'}.` };
  }
  if (!userId) return { success: false, message: 'User ID is required.' };

  try {
    const { data, error } = await supabase
      .from('participations')
      .select('*') 
      .eq('user_id', userId)
      .order('participated_at', { ascending: false });

<<<<<<< HEAD
    if (error) throw error;
=======
    const participations: any[] = [];
    querySnapshot.forEach((docSnap) => { // Renamed doc to docSnap
      const data = docSnap.data();
      const convertTimestamp = (timestamp: Timestamp | string | null | undefined): string | null => {
        if (timestamp instanceof Timestamp) {
          return timestamp.toDate().toISOString();
        }
        return typeof timestamp === 'string' ? timestamp : null;
      };
      participations.push({
        id: docSnap.id,
        ...data,
        participatedAt: convertTimestamp(data.participatedAt),
      });
    });
>>>>>>> f5b34cc (I see this error with the app, reported by NextJS, please fix it. The error is reported as HTML but presented visually to the user).)

    const participations: ParticipationData[] = data || [];
    console.log(`[Supabase Service] getParticipationData: Fetched ${participations.length} participations for user ${userId}.`);
    return { success: true, participations };
  } catch (error: any) {
    console.error('[Supabase Service Error] Error fetching participations:', error.message, error.stack);
    return { success: false, message: `Could not fetch participation data: ${error.message || 'Unknown error'}` };
  }
}

<<<<<<< HEAD
/**
 * Fetches a single event by its ID.
 */
export async function getEventById(eventId: string): Promise<{ success: boolean; event?: EventData; message?: string }> {
    console.log(`[Supabase Service - Events] getEventById invoked for ID: ${eventId}`);
    if (supabaseError || !supabase) return { success: false, message: `Supabase error: ${supabaseError?.message || 'Client not initialized'}` };
    if (!eventId) return { success: false, message: 'Event ID is required.' };

    try {
        const { data, error } = await supabase
            .from('events')
            .select('*')
            .eq('id', eventId)
            .single();

        if (error) {
             if (error.code === 'PGRST116') return { success: false, message: 'Event not found.' }; // No rows found
            console.error(`[Supabase Service Error - Events] Error fetching event ${eventId}:`, error.message);
            throw error;
        }
        return { success: true, event: data as EventData };
    } catch (error: any) {
        console.error(`[Supabase Service Error - Events] Catch block error fetching event ${eventId}:`, error.message);
        return { success: false, message: `Failed to fetch event: ${error.message}` };
    }
}
=======
    
>>>>>>> f5b34cc (I see this error with the app, reported by NextJS, please fix it. The error is reported as HTML but presented visually to the user).)
